---
title: "Testing rBeale"
author: "Colleen Cosgrove"
date: "2023-09-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r texting code}
library(blastula)
# store credentials to later send our message via smtp (using gmail here but could be others)
create_smtp_creds_file(
  file = "gmail_creds",
  user = "ccosgrov@heidelberg.edu",
  provider = "gmail"
  #pass because fuck google: fing skky wach vacn
)

sendtext = compose_email("R has stopped")
sendtext %>%
  smtp_send(
    to = "2034700303@vtext.com", 
    from = "ccosgrov@heidelberg.edu",
    credentials = creds_file("gmail_creds")
  )
```

 General comments/thoughts/ideas that might hopefully be worthwhile
1. It would be cool to be able to (and maybe already in the plan?) to use the rshiny interface to pull data and then load it right into the code - obvi that would change some of the code, but it would be dope as hell and *so* much faster.
2. 
3. 

```{r set up}
#first create a list of rivers to use.
##let's use fewer than all the rivers just to check that things are working..
input_rivers=c("Beaver")


##This is a master list of all the rivers that we have on the HTLP for future reference and less typing later.
#input_rivers=c("Beaver", "Blanchard", "Chickasaw", "Coldwater", "Cuyahoga", "Grand Lake St Marys", "Grand River", "Great Miami", "Honey Creek", "Huron River", "Lost", "Maumee", "Muskingum", "Portage", "Potato Run", "Raisin", "Rock Creek", "S Turkeyfoot", "Sandusky", "Scioto Chilicothe", "Scioto Piketon", "Shallow Run", "Tiffin", "Vermillion", "West")

#parent directory
setwd("C:/Users/ccosgrov/Documents/GitHub/rbeale/rbeale data")
parent_directory = getwd()
```


```{r annual}
#run the actual code
annual(parent_directory, input_rivers)
#run all the functions, the code works. That's great.

sendtext %>%
  smtp_send(
    to = "2034700303@vtext.com", 
    from = "ccosgrov@heidelberg.edu",
    credentials = creds_file("gmail_creds")
  )
```

```{r monthly}
#the above data should still work, so let's do the things.
monthly(parent_directory, input_rivers)

sendtext %>%
  smtp_send(
    to = "2034700303@vtext.com", 
    from = "ccosgrov@heidelberg.edu",
    credentials = creds_file("gmail_creds")
  )
```

```{r spring}
#the above data should still work, so let's do the things.
spring(parent_directory, input_rivers)

sendtext %>%
  smtp_send(
    to = "2034700303@vtext.com", 
    from = "ccosgrov@heidelberg.edu",
    credentials = creds_file("gmail_creds")
  )
```

```{r daily}
#the above data should still work, so let's do the things.
daily(parent_directory, input_rivers)

sendtext %>%
  smtp_send(
    to = "2034700303@vtext.com", 
    from = "ccosgrov@heidelberg.edu",
    credentials = creds_file("gmail_creds")
  )
```
